### PR TITLE
Add notes about load balancing mechanism

### PR DESCRIPTION
**Pull request by dcreager**
This adds some informative notes about Reporting's failover and load balancing mechanism: that it's the same as that provided by DNS SRV records, and that in the future, we'd ideally want this to be a more generic feature of Fetch.

***
<a href="https://pr-preview.s3.amazonaws.com/dcreager/reporting/pull/94.html" title="Last updated on Jul 7, 2018, 1:52 PM GMT (bbf2aad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/reporting/94/3191fc4...dcreager:bbf2aad.html" title="Last updated on Jul 7, 2018, 1:52 PM GMT (bbf2aad)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
I thought the idea was to mark the whole thing as a possible v2 feature?

**Comment by dcreager** [comment]
Oh, no I was thinking that moving it from Reporting to Fetch was the v2 feature.  We already have something reasonable spec'ed and implemented; I was using the references to SRV to highlight that we're not proposing something new and untested, we're using the current accepted practice for doing this client-side.

**Comment by annevk** [comment]
We should probably go back to the issue discussion then...

**Comment by dcreager** [comment]
Per the discussion in #93, we're going to keep the current load balancing / failover text here in Reporting, and I've opened whatwg/fetch#775 to discuss whether we can move it into Fetch / Origin Policy at some point in the future.

**Pull request merged**
